# Generated by Django 3.0.2 on 2020-01-04 10:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_game_status"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="game", managers=[("manager", django.db.models.manager.Manager()),],
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("F", "First Player To Move"),
                    ("S", "Second Player To Move"),
                    ("W", "First Player Wins"),
                    ("L", "Second Player Wins"),
                    ("D", "Draw"),
                ],
                default="F",
                max_length=1,
            ),
        ),
    ]
